### ISSUE TITLE
Does not work with Castle.Windsor V3

### ISSUE THREAD

**Issue by PapaMufflon** [bszafko/PrismContrib.WindsorExtensions#8]
As I can see, there is no Castle.Windsor.InitializationException anymore and

Container.Register(AllTypes.FromAssemblyContaining<IRegionAdapter>().BasedOn<IRegionAdapter>()
                    .Configure(c=>c.LifeStyle.Transient));

 should be changed to

Container.Register(AllTypes.FromAssemblyContaining<IRegionAdapter>().BasedOn<IRegionAdapter>()
                    .LifestyleTransient());

**Comment by bszafko** [comment]
just noticed this is unclosed ?

closing this for now
